.PHONY: clean help

help: help.txt
	@cat help.txt


clean:
	rm -rf build/;
	#rmdir -f build;

build: clean
	#rmdir build;
	mkdir build;
	cd build/;
	#compila il file c in questa cartella e rendilo eseguibile
	#touch pmanager;
	#chmod +x pmanager;
